### ISSUE TITLE
Bounds ordonnés

### ISSUE THREAD

**Issue by emmakopp1** [emmakopp1/phylogeny_trust#10]
J'ai fait tourné ton fichier `temp.R` mais il y a quelque chose qui ne me parait pas cohérent sur le plot de `ub_DS` : 
La borne tends vers 0.9999875 or sur le fichier `st_ctmc-strict-bd-fossilRemoved.log`, on voit que le paramètre `pi_0` est 0.942. 
Donc lorsque t est grand (20 environ), la borne devrait tendre vers 0.942. Or ce n'est pas le cas
Qu'en penses-tu?

**Comment by tpellard** [comment]
Oui il y avait une erreur, merci. Il fait rajouter `rowwise()` avant le calcul des bornes pour que R fasse bien le calcul ligne par ligne.

Par contre le résultat n'est pas super et est difficile à interpréter. Vu que la borne tend toujours vers π₀ qui est toujours supérieur à 0.9, on ne sait pas trop quoi en dire

**Comment by emmakopp1** [comment]
je n'ai rien d'actualisé dans mes figures sur le github

**Comment by tpellard** [comment]
Oui J'ai pas mis à jour le code des figures, je m'en occupe ce week-end

**Comment by tpellard** [comment]
Fait. J'ai mis les subsets bantous dans la meme figure pour voir, mais on peut les remettre à part aussi
