### ISSUE TITLE
Nombre de cognats dans les données simulées

### ISSUE THREAD

**Issue by tpellard** [emmakopp1/phylogeny_trust#11]
L'article dit qu'on a généré des cognat dans la simulation mais ne dit pas combien. Est-ce qu'on a l'info dans un fichier quelquepart? ça permettrait aussi de calculer la borne de Δ^T pour les données simulées

**Comment by emmakopp1** [comment]
Oui dans `tree_sim.nex` dans le fichier `preprocess_simulated_data` : 

`#NEXUS

BEGIN DATA;
 DIMENSIONS NTAX=50 NCHAR=**3784**;
 FORMAT DATATYPE=BINARY GAP=- MISSING=?;
 MATRIX`

**Comment by tpellard** [comment]
Ah oui désolé, je n'avais pas cherché dans ce dossier
