### ISSUE TITLE
Paramètres depuis Tracer

### ISSUE THREAD

**Issue by tpellard** [emmakopp1/phylogeny_trust#13]
En extrayant les données, j'ai calculé la moyenne de π₀, π₁ et de t_R. Est-ce correct ou vaut-il mieux prendre par exemple la médiane? Pour l'âge en tout cas il me semble qu'on parle plus souvent de la médiane

**Comment by emmakopp1** [comment]
j'ai pas d'avis, il faudra demander à robin
