### ISSUE TITLE
Âges des arbres simulés

### ISSUE THREAD

**Issue by tpellard** [emmakopp1/phylogeny_trust#14]
L'article décrit qu'on a simulé des arbres d'âge de 1 à 17 millénaires, chacun des `tree-sim-i.tree`. Mais les âges moyens des résultats de beast sont assez différents: 

| family|       pi0|       pi1|       t_R|
|------:|---------:|---------:|---------:|
|      1| 0.5005173| 0.4994827|  4.087380|
|      2| 0.5009848| 0.4990152|  4.328674|
|      3| 0.5006531| 0.4993469|  4.131720|
|      4| 0.4982740| 0.5017260|  4.278868|
|      5| 0.5012455| 0.4987545|  4.145915|
|      6| 0.5013594| 0.4986406|  4.997658|
|      7| 0.5007808| 0.4992192|  6.714967|
|      8| 0.5003334| 0.4996666| 13.526969|
|      9| 0.4975249| 0.5024751| 15.235329|
|     10| 0.4995509| 0.5004491| 18.892063|
|     11| 0.5022454| 0.4977546| 19.789334|
|     12| 0.5021514| 0.4978486| 31.937666|
|     13| 0.5017466| 0.4982534| 21.720497|
|     14| 0.4997428| 0.5002572| 16.153669|
|     15| 0.5011629| 0.4988371| 27.604187|
|     16| 0.5015785| 0.4984215| 31.504883|
|     17| 0.4959604| 0.5040396| 21.971150|

**Comment by emmakopp1** [comment]
Oui ils le sont. Cela peut être du au fait que dans les étude je n'ai mis qu'une seule calibration. Cependant étant donné que l'on cherche à reconstruire la topologie des noeuds profond, ce n'est pas vraiment un problème.

**Comment by tpellard** [comment]
Si on veut faire un diagramme des bornes sur les données simulées, on prend quel age? L'age connu ou l'age inféré?

**Comment by emmakopp1** [comment]
Je ne sais pas si cela a un intêret de faire des bornes sur les données simulés car le but est de montrer que l'on ne peut pas reconstruire la topologies profonde. Donc on vérifie empiriquement des résultats théoriques. 
Je ne vois pas ce que cela ajoute puisque de toute façon l'âge inféré est mauvais. Ou alors on fait varier l'age entre 0 et 20 aussi mais je ne sais pas
