### ISSUE TITLE
problème lecture d'arbre

### ISSUE THREAD

**Issue by emmakopp1** [emmakopp1/phylogeny_trust#15]
Bonjour, 

Je n'arrive plus à lire aucun fichier .trees depuis mon retour du dejeuner. 

`> trees =  ape::read.tree(here("data/real/st_ctmc-strict-bd-fossilsRemoved/st_ctmc-strict-bd-fossilRemoved.trees"))
Error in if (all(phy$node.label == "")) phy$node.label <- NULL : 
  missing value where TRUE/FALSE needed`

Quelqu'un a une idée du problème ?

**Comment by tpellard** [comment]
Oui moi aussi j’ai eu des problèmes, essaie avec les fonctions du package treeioLe 19 avr. 2024 à 13:42, Kopp ***@***.***> a écrit :﻿
Bonjour,
Je n'arrive plus à lire aucun fichier .trees depuis mon retour du dejeuner.
> trees =  ape::read.tree("/Users/kopp/Documents/phylogeny_trust_local/beast/sino-tibet-ctmc-strict-bd-fossilsRemoved/sino-tibetan-ctmc-strict-bd.trees") Error in if (all(phy$node.label == "")) phy$node.label <- NULL :  missing value where TRUE/FALSE needed
Quelqu'un a une idée du problème ?

**Comment by emmakopp1** [comment]
ça marche pas, très étrange
