### ISSUE TITLE
Nouvelle borne ∆S

### ISSUE THREAD

**Issue by emmakopp1** [emmakopp1/phylogeny_trust#17]
Bonjour, 
J'ai implémenté la nouvelle borne pour calculer ∆S en prenant en compte les fossils `compute_upperbound_DS_2.` 
Malheureusement, elle nécessite de charger les arbres. 
Je ne suis pas sûre d'avoir le niveau pour modifier `get_all_parameters` dans `temp.R`, un peu d'aide serait la bienvenue...
Bonne journée !

**Comment by tpellard** [comment]
Si je comprends bien le code, il faut les âges de chaque arbre de l'échantillon postérieur, c'est ça? On met un burn-in?
Pour accélérer le code, or pourrait en fait lire les fichiers .trees, extraire les infos et les écrire dans un tableau qu'on réimporte ensuite. Comme ça on n'a pas besoin de réimporter à chaque fois les .trees

**Comment by tpellard** [comment]
Et cette fonction on va l'utiliser uniquement sur les résultats de modèles FBD ou bien elle a vocation à remplacer totalement la précédente?

**Comment by emmakopp1** [comment]
Cette fonction sera utilisée pour ∆S qui utilisera exclusivement des modèles d'arbres FBD. Donc elle va remplacer `compute_upperbound_DS`. 

Très bonne idée oui de lire les fichiers d'arbres. Je propose 20% de burnin si ce n'est pas déraisonnable niveau temp de calcul. Car la façon dont je l'ai faite c'était impossible j'ai fini par prendre uniquement le dernier arbre.
