### ISSUE TITLE
Mise à jour des données

### ISSUE THREAD

**Issue by tpellard** [emmakopp1/phylogeny_trust#18]
@emmakopp1 Pour plus de clarté, il vaut mieux effacer les jeux de données que l'on n'utilise plus. Il faut aussi envoyer par FileSender les fichiers trees nouvellement obtenus

**Comment by emmakopp1** [comment]
yes, work in progress...
Les études bantoue et sino-tibetaine sont définitives

**Comment by tpellard** [comment]
Je suis un peu perdu avec tous les jeux de données, lesquels sont à analyser et lesquels sont à ignorer?

**Comment by emmakopp1** [comment]
analyser : 
- bantu (tous)
- st_ctmc-strict-fbd
Work in progress : 
- tea_ctmc-strict-fbd-constrained
- iecor_ctmc-strict-fbd
Le reste va probablement partir mais j'attend d'être sure que l'on peut s'en sortir avec le modèle FBD pour les deux bornes

**Comment by emmakopp1** [comment]
J'ai cleané les fichier. 

Étude définitive : bantoue, sino-tibétaine
Études dont on attend les résultats : Iecor,tea

Les outputs indo-européens arrivent bientôt, pour l'analyse des langues transeurasienne, c'est extremement long...
