### ISSUE TITLE
Temps de calcul

### ISSUE THREAD

**Issue by emmakopp1** [emmakopp1/phylogeny_trust#19]
J'ai ajouté `compute_upperbound_DS_2` qui prend en compte les données fossiles pour calculer Delta S. 
Néanmoins cela nécessite de load les arbres eet cela rajoute un temps de calcul non négligeable. 
As-tu une idée de comment palier ce problème ?

**Comment by tpellard** [comment]
Je m'y mets lundi. Ma solution serait de lire tous les arbres et d'extraire leur âge, de mettre ça dans un tableau avec les valeurs extraites du .log, et d'écrire ça dans un fichier. Ça prendra du temps mais on n'a besoin le faire qu'une fois, après on importe les données du fichier créé, ce qui sera rapide.

**Comment by emmakopp1** [comment]
Oui je pense que c'est la bonne solution. 

Concernant la borne sur la topologie on va intégrer un treshold temporel `s` qui s'explique comme cela : a droit de s je connais la topologie et a gauche de s je connais pas la topologie. On en a déjà parlé une ou deux fois. 

C'est encore en reflexion mais ce `s` risque de correspondre à l'âge du fossil le plus vieux. 
Donc j'intègre au code le `s` en question (dans les fonctions) puis dans un second temps ce calcul d'age des fossils avec tibble si j'y arrive

A bientot

**Comment by tpellard** [comment]
Le fichier log semble inclure l'age de chaque arbre (TreeHeight.t.tree), du coup on n'aurait pas besoin de lire les fichiers trees non?

**Comment by emmakopp1** [comment]
Malheureusement on veut l'âge de chaque feuille...

**Comment by tpellard** [comment]
OK je vois le problème meme avec les fichiers légers du subset bantou...

**Comment by emmakopp1** [comment]
Oui... 
Ce qu'on peut faire c'est regarder sur une centaine d'abres par dataset.
La librarie rwty permet de lire un fichier d'abre en conservant 1 arbre sur 100 (par exemple) comme cela : 
`rwty::load.trees(file,trim=100)`
Cela pourrait nous permettre de cacluler des âges plus rapidement mais le chargement des arbres reste long... 

Par ailleurs cette librairie permet aussi de lire les fichiers log et de faire des choses similaire à tracerer. 

Aussi, je pense qu'on peut supprimer mon code d'avant et intégrer à part entière `temp.R `

**Comment by tpellard** [comment]
Bon ca fait plus d'1h30 que ma machine tourne sur le bantou complet, il va falloir trouver une autre manière de faire. On sélectionne 1000 arbres de chaque jeu de données ou bien une proportion identique du jeu complet?

**Comment by tpellard** [comment]
J'ai interrompu le processus au bout de 2h30...
La bonne nouvelle c'est que lire le fichier trees du bantou complet prend 3 minutes avec treeio::read.nexus().
La mauvaise nouvelle est qu'obtenir les ages des feuilles sur un sous-ensemble de 1000 arbres bantous prend 1h.
On a besoin des ages des feuilles de chaque arbre? Une moyenne ou médiane ne suffit pas? Et pour les langues bantoues, si toutes les langues sont modernes, elles ont le meme age qui est l'opposé de celui de la racine non?

**Comment by tpellard** [comment]
Bonne nouvelle, j'ai trouvé la fonction `node.depth.edgelength()` de `ape` qui fait la meme chose que `distRoot()` mais est beaucoup plus rapide. Sur le jeu complet des 57120 arbres bantous, ca prend 86s sur ma machine :-)

**Comment by tpellard** [comment]
Moyenne nouvelle, le fichier csv des ages de toutes les feuilles de tous les arbres bantous fait 873MB. En comprimant le fichier en bz, on passe à 60MB, 50MB en xz, et 7MB en format binaire .rds comprimé en xz, mais dans tous les cas la compression prend un peu de temps en plus.

Evidemment il n'y a pas de problème si on choisit de travailler avec un échantillon

**Comment by emmakopp1** [comment]
very good news ! 
Merci 
Option 1 : on utilise la librairie `rwty` qui permet de sélectionner 1 arbre sur X. Cela permet de conserver de bonne propriétés. 
Option 2 : on met un gros burnin (90%) en vérifiant préalablement que les métrique (ESS,Trace) restent bonnes. 

Qu'en penses-tu ?

**Comment by tpellard** [comment]
Je n'ai pas d'avis, c'est plutot une question pour toi et Robin. Il est envisageable de conserver tous les arbres bantous, mais juste ca peut prendre 5 minutes pour exporter et réimporter les données
