### ISSUE TITLE
Infos sur config.json

### ISSUE THREAD

**Issue by tpellard** [emmakopp1/phylogeny_trust#2]
Comment obtient-on le fichier `src/compute_bounds/config.json`? D'où viennent les informations qui y figurent?
De plus, les valeurs ne sont pas associées à des noms de variable, ce qui rend le fichier difficilement interprétable.

**Comment by emmakopp1** [comment]
C'est moi qui les rentres manuellement
Les valeurs sont associées aux noms de chaque dataset. Mais on peut changer si tu veux

**Comment by tpellard** [comment]
Pour améliorer la reproductibilité il vaudrait mieux extraire ces valeurs avec un script qui ensuite les écrit dans `config.json`. Elles viennent d'où ces valeurs?

**Comment by emmakopp1** [comment]
paramètres correspondent aux outputs de beast, sinon c'est des chemin vers les fichiers trees

**Comment by tpellard** [comment]
Concrètement c'est à quel endroit de quel fichier beast pour le sino-tibétain par exemple?

**Comment by emmakopp1** [comment]
Pour un dataset (ici sino-tibetain): 

"sino-tibetan": [
      "data/real/sino-tibet-ctmc-strict-bd-fossilsRemoved/sino-tibetan-ctmc-strict-bd.trees", **chemin vers le fichiers d'arbre**
      "0.942", **paramètre pi0 dans le modèle de substitution**
      "5.84e-2", **paramètre pi1 dans le modèle de substitution**
      "3785", **nombre de traits**
	"src/cognat_survival_prob/cognates_data/cognates_st.txt", ** lien vers le fichier texte de cognat **
	"8.867" **age de la racine après l'inférence **

NB : src/cognat_survival_prob/cognates_data/cognates_st.txt ce fichier est utilisé dans cognat_survival_prob pour calculer le nombre de sens communs entre les feuiiles

**Comment by tpellard** [comment]
Pardon je m'exprime mal, je veux dire px ex. la valeur "0.942" pour pi0, on peut la trouver à quel endroit de quel fichier output de beast?

**Comment by emmakopp1** [comment]
Ah pardon. Il faut load le fichier .log sur Tracer et mettre  20% de burn-in

**Comment by tpellard** [comment]
Il s'agit donc bien ici des valeurs freqParameter.s.sino.tibetan.1, freqParameter.s.sino.tibetan.2, et TreeHeight.t.tree. Le nombre de traits par contre n'est pas dans le log n'est-ce pas.

**Comment by emmakopp1** [comment]
Exact

De : Thomas Pellard ***@***.***>
Date : mercredi, 17 avril 2024 à 13:50
À : emmakopp1/phylogeny_trust ***@***.***>
Cc : Emma Kopp ***@***.***>, Comment ***@***.***>
Objet : Re: [emmakopp1/phylogeny_trust] Infos sur config.json (Issue #2)

Il s'agit donc bien ici des valeurs freqParameter.s.sino.tibetan.1, freqParameter.s.sino.tibetan.2, et TreeHeight.t.tree. Le nombre de traits par contre n'est pas dans le log n'est-ce pas.

**Comment by tpellard** [comment]
Je ne trouve pas les paramètres freqParameterXXX dans les fichiers log pour l'indo-européen

**Comment by emmakopp1** [comment]
oui j'avais fait une analyse avec un modèle covarion (erreur), je m'en suis aperçue hier donc je l'ai relancé ce matin. 
On aura les résultats dans quelques jours
