### ISSUE TITLE
Erreur à la lecture de iecor.nex

### ISSUE THREAD

**Issue by tpellard** [emmakopp1/phylogeny_trust#23]
Dans `01_Import.R` le code `get_nexus_parameters()` plante sur `iecor.nex`:

```
 get_nexus_parameters(here("data/real/iecor_ctmc-strict-M1/iecor.nex"))

> Erreur dans cslEscaped[character_num, 2] : indice hors limites
```

Ça plante en fait dans la fonction à l'import du fichier avec `ReadAsPhyDat()` de `TreeTools`:

```
 ReadAsPhyDat(here("data/real/iecor_ctmc-strict-M1/iecor.nex"))

> Erreur dans cslEscaped[character_num, 2] : indice hors limites
```

C'est sans doute un problème de format du fichier nexus. En l'ouvrant à la main on voit qu'il n'est pas comme les autres, et c'est le seul à avoir la mention `[ Generated by: CoBL ]`.

**Comment by emmakopp1** [comment]
Problème reglé, j'ai modifié à la main le fichier .nexus en enlevant la partie characterlabels. 
J'ai peur que ça pose problème pour obtenir des informations trait par trait...
Mais c'est le mieux que j'ai trouvé pour le moment.
