### ISSUE TITLE
Valeurs de `depth` avec `get_tip_ages()`

### ISSUE THREAD

**Issue by tpellard** [emmakopp1/phylogeny_trust#28]
Dans `src/01_Import.R`, on vient de rajouter le calcul d'une valeur `depth` dans la fonction `get_tip_ages()`:

```
depths <- max(ages) - ages
```

Quand on regarde les résultats, on voit que les langues modernes n'ont pas 0 mais une valeur de l'order de 10¹⁵ ou 10¹⁶. C'est normal? Si c'est dû à des problèmes d'arrondis, on peut aussi arrondir cette valeur dans le calcul (ici avec deux décimales):

```
depths <- round(max(ages) - ages, 2)
```

**Comment by emmakopp1** [comment]
Ok, 
Tu peux ajouter les depth pour le bantu stp tu l'as oublié
