### ISSUE TITLE
Fichiers nexus

### ISSUE THREAD

**Issue by tpellard** [emmakopp1/phylogeny_trust#4]
Ce serait utile de mettre les fichiers nexus des matrices langues × traits sur le dépôt pour ne pas avoir forcément à ouvrir les gros fichiers .trees

**Comment by tpellard** [comment]
@emmakopp1 Si j'ai bien compris, `get_tree_param()` sert surtout à obtenir le nombre de feuilles N. Mais comme la fonction demande d'ouvrir chacun des gros fichiers `.trees`, ce qui ralentit le code. Avec les fichiers `.nex` on pourrait obtenir le nombre de feuilles N beaucoup plus vite

**Comment by emmakopp1** [comment]
oui, je le fais ?

**Comment by tpellard** [comment]
Oui stp, après je m'occupe de rédiger le code pour intégrer tout ça (dans mon fichier `temp.R` pour l'instant

**Comment by emmakopp1** [comment]
petit soucis, tous les fichiers nexus ne sont pas lisible par la fonction read.nexus.data, notamment le fichier transeurasien 
du fait du format. As-tu une alternative ?

**Comment by emmakopp1** [comment]
c'est push, la fonction s'appelle `n_extant_language` juste en dessous de `get_tree_param`. 
Je m'occupe à présent d'ajouter tous les fichiers nexus et de vérifier qu'ils soient cohérent (fossiles enlevés etc)

**Comment by tpellard** [comment]
Effectivement c'était pas évident mais avec le code ci-dessous ça marche:

```
library(TreeTools)
ReadAsPhyDat(here("data/real/trans-ctmc-strict-fbd/data2.nex"))
```

**Comment by emmakopp1** [comment]
merci
