### ISSUE TITLE
New bounds

### ISSUE THREAD

**Issue by emmakopp1** [emmakopp1/phylogeny_trust#5]
J'ai push sur github les fonctions qui permettent d'obtenir les nouvelles bornes. 
En revanche, je n'arrive pas à obtenir les plots
il me semble que cela vient de bounds_tb, ligne 52 de compute_bounds.R

**Comment by tpellard** [comment]
Tu peux poster le message d'erreur stp?

**Comment by emmakopp1** [comment]
Error in arrange(mutate(map_df(dt_params, ~tibble(t = .x$t, k = .x$k,  : 
  could not find function "arrange"
> write_csv(bounds_tb, here("output/results/bounds_tb.csv"))
Error in write_csv(bounds_tb, here("output/results/bounds_tb.csv")) : 
  could not find function "write_csv"

**Comment by tpellard** [comment]
Chez moi ca marche, mais il fallait au préalable rajouter les paramètres pi0 et pi1 aux fonctions compute_upper_bound_ et find_t_value_. Mais ton message d'erreur indique qu'il ne connait pas les fonctions arrange() et write_csv() qui devraient pourtant etre chargées par library(tidyverse)

**Comment by emmakopp1** [comment]
mais du coup dans le fichier `fig_bounds.pdf` on devrait avoir une ordonnée entre 0.9 et 1 et pas entre 0.5 et 1 
J'ai l'impression que ça ne marche pas bien du coup

**Comment by emmakopp1** [comment]
pourtant quand je calcule les bornes sur le fichier `compute_bounds.R` j'ai des nouvelles bornes autour de 0.9

**Comment by tpellard** [comment]
J'essaie de relancer le code pour identifier les problèmes mais le fichier  `functions.R` appelé par `compute_bounds.R` appelle une variable `path_nex` non-définie:

````
> data_st <- get_tree_par_fun(path_to_config, "sino-tibetan", n_tree = 1)
Erreur dans get_tree_param(tree, data$pi0, data$pi1, data$k, data$t_conv) : 
  objet 'path_nex' introuvable
````

De mon côté j'ai tout réimplémenté à ma sauce dans `temp.R`. J'utilise beaucoup les fonctions du `tidyverse` et je fonctionne avec des tableaux plutôt que les listes. Tu peux jeter un coup d'œil @emmakopp1

**Comment by tpellard** [comment]
> mais du coup dans le fichier fig_bounds.pdf on devrait avoir une ordonnée entre 0.9 et 1 et pas entre 0.5 et 1

Avec mon nouveau code, c'est bon, je vais mettre à jour les figures
