### ISSUE TITLE
Fichiers auxiliaires

### ISSUE THREAD

**Issue by tpellard** [emmakopp1/phylogeny_trust#8]
A-t-on besoin des petits fichiers .SBATCH et .xml.state (et ceux avec un numéro derrière)? Ils servent à quoi?
Et les fichiers .out? Et le fichier bantu-study.out se termine par un message d'erreur, c'est normal?

**Comment by emmakopp1** [comment]
non pas besoin ! 
Oui l'erreur est du à l'équipe informatique de dauphine qui avait fermé le cluster. Toute les analyses en cours s'étaient donc arrêtés avec ce message d'erreur

**Comment by tpellard** [comment]
Du coup on peut les effacer? Faut-il garder les .out pour conserver chaque *seed*?

**Comment by emmakopp1** [comment]
On peut les effacer. Concernant la seed, je ne sais pas. Je crois qu'on s'en fiche un peu. Du moins je ne m'en suis jamais servi
