### ISSUE TITLE
Conventions pour les noms des fichiers

### ISSUE THREAD

**Issue by tpellard** [emmakopp1/phylogeny_trust#9]
Les noms de fichiers BEAST ne sont pas unifiés (ex: `data2.nex` pour le transeurasien, `bantu.nex` mais `ctmc-strict-bd.log` pour le bantou…)

Je propose que chaque fichier commence par un préfixe de nom de la famille, suivi d'un `_`, et ensuite on peut garder des abbréviations des propriétés du modèle du type `ctmc-strict-bd`:

- `bantu_` pour le bantou
-  `iecor_` pour l'indo-européen
-  `st_` pour le sino-tibétain
-  `tea_` pour le transeurasien

**Comment by emmakopp1** [comment]
Très bien, je le fais ?

**Comment by tpellard** [comment]
stp
